### PR TITLE
fixed FormatNegotiator, Gzip and Minify execution order

### PR DESCRIPTION
**Pull request by schnittstabil**
Same as f9eaf5bacd02b596f6ea5910ddad27b4a2a68c6a.

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi @schnittstabil 
Thanks for your contribution, but I'm not sure if this this a good idea. Let's take the following scenario:

``` php
$middlewares = [
    Middleware::minify(),

    function ($request, $response, $next) {
        $minifiedContent = (string) $response->getBody();

        return $next($request, $response);
    }
];
```

In this case, the `$minifiedContent` variable contains the unminified content because the previous middleware is executed after it. This is the confusing thing about this onion style middlewares. So, I try to follow the following rule:

> If the logic of a middleware can be executed in one step, execute always before the nested middlewares

This allows to insert the middlewares in a more intuitive order.

``` php
$middlewares = [
    Middleware::formatNegotiator(), //resolve the content type
    Middleware::fastRoute($route),  //execute the routes
    Middleware::minify(),           //minify the result
    Middleware::gzip(),             //gzip compress the minified content
];
```

This is what I try to do, but I'm open to discussion if you think there's a better way.

**Comment by wolfy-j** [comment]
I agree with pull request author, gzip and minification middlewares are modification wrappers. Putting them to top of chain has more sense as in this case you declares that all content generated by your pipeline has to be modified.

If you not doing so, you will have to insert new middleware in a middle of your chain, which is not very obvious.

I think the general confusion is about mixing endpoints (middlewares containing application) and filters (wrappers).

**Comment by wolfy-j** [comment]
In Zend Expressive (as in framework i'm using) there is no middlewares after endpoint found (which is right, endpoint middleware should not decide if it enabled or not):

chain 

Meaning you will not be able to use your version gzip and minify wrappers in flow, as they need to be in green area.

In my opinion more obvious flow is:

REQUEST -> [YOUR MIDDLEWARES] -> **[APP OR ROUTER -> inner middlewares -> endpoint/controller/action]:RESPONSE** -> [YOUR MIDDLEWARES] -> RESPONSE TO CLIENT

Where your middlewares is wrappers, auth, session wrappers and etc. So it's nested tree, not linear process.

``` php
$pipeline = new MiddlewarePipeline([
    new GzipMiddleware(),
    new MinifyMiddleware(),
    new SessionStarter(),
    new WhoopsHandler()
]);

$response = $pipeline->target(new Router(...))->run($request, $response);
```

What do you think?

**Comment by schnittstabil** [comment]
> This allows to insert the middlewares in a more intuitive order.

``` php
$middlewares = [
    Middleware::formatNegotiator(),
    Middleware::fastRoute($route),
    Middleware::minify(),
    Middleware::gzip(),
];
```

Despite it is not possible in Slim and Zend Expressive, IMO it is not more intuitive.
E.g.: Where should we put an auth middleware?
- Before `Middleware::gzip()` means that rejected requests are not gzipped 
- After `Middleware::gzip()` means that the auth middleware can't write an error message to the body, because it is already gzipped

**Comment by oscarotero** [comment]
Ok, I always considered the router middleware like any other middleware, but may be wrong. I not full convinced yet with this approach, but if Slim, Zend Expressive and other frameworks works like this, and people understand that this is the way it should to be, I'm ok with this.

Thanks for the feedback

**Comment by schnittstabil** [comment]
Many thanks for v3.12.4.

**Comment by oscarotero** [comment]
You're welcome

**Pull request merged**
