### PR TITLE
Update fast-route dependency

### PR DESCRIPTION
**Pull request by sander-bol**
Update dependency on nikic/fast-route from "0.*" to "^0.7" to resolve conflict with "league/route".

### CODE REVIEW

**Comment by sander-bol** [comment]
@oscarotero Could you merge this one? This broken dependency is breaking all builds currently, as mentioned in #46

**Comment by abacaphiliac** [comment]
+1

**Comment by oscarotero** [comment]
Merged!. Thank you. I'm curious about the reason why `league/route` does not use the latest version of `fast-route`. The [version 2.0](https://github.com/thephpleague/route/releases) has been released yesterday and it still using the `0.7` version.

**Comment by abacaphiliac** [comment]
@oscarotero let's find out together!
https://github.com/thephpleague/route/pull/135

seems that league's route works with lots of fast-route versions including the most recent tags. i added highest and lowest dependency version builds. looks like the package has pretty good coverage, so we'll see what they say : )

**Comment by abacaphiliac** [comment]
@oscarotero my change to thephpleague/route was accepted. we might be able to loosen the dependency range now.

**Pull request merged**
