### PR TITLE
Ip detect options

### PR DESCRIPTION
**Pull request by wolfy-j**
Hi, i had a moment to work on #65

### CODE REVIEW

**Comment by oscarotero** [comment]
Thanks for your work, @wolfy-j but I'm not convinced about this change. All server parameter but `REMOTE_ADDR` can get from headers. For example, `HTTP_X_FORWARDED_FOR` can be taken from `X-Forwarded-For` header, so there's no need to handle servers parameters. The only exception is `REMOTE_ADDR`, that contains the ip of the TCP connection and it's something outside of any http header. [more info](http://stackoverflow.com/questions/4773969/is-it-safe-to-trust-serverremote-addr#4773981).

I prefer an option called `->proxy()`, that if it's true, use these proxy headers and let the `REMOTE_ADDR` as the final choice, instead the first. See, for example: https://github.com/akrabat/rka-ip-address-middleware

**Comment by wolfy-j** [comment]
Sure, i haven't work with ip detection for while, you can remove PR if it can be re-configured other way.

**Comment by wolfy-j** [comment]
Thought, server will usually duplicate ENV variables which might include ip address as well in environments where no correct header are set.

**Comment by Overtorment** [comment]
@wolfy-j  not sure if thats relevant, improved IP detection (works with behind reverse proxies) was merged to master recently

**Comment by wolfy-j** [comment]
@Overtorment yeah, i'v already checked it and i like the outcome 👍

**Pull request closed without merging**
