### PR TITLE
AttributeMapper middleware

### PR DESCRIPTION
**Pull request by wolfy-j**
This addresses my issue of letting developer to use implementaion specific attributes as regular attributes. However i'm not sure if AttributeRouter is very good name (can be confused with other Routers).

You can see sample usage in test.

### CODE REVIEW

**Comment by wolfy-j** [comment]
Maybe AttributeMapper is better name.

**Comment by oscarotero** [comment]
I really like the idea! :+1:

**Comment by wolfy-j** [comment]
Let update docs then, 5 min.

**Comment by wolfy-j** [comment]
Done.

**Pull request merged**
